---
title: "Schedule"
date: "1/10/24"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    # toc: true
editor_options: 
  chunk_output_type: console
---

* _Schedule is subject to change._ 
* Links have been added to all weeks, but weeks we have not covered yet will have broken links.

|          Week           | Date | Topics                                                                                                                | Classroom         | Instructor |
|:------------:|:------------:|:----------------|:-------------|--------------|
| [1](weeks/week_01.qmd)  | 1/10 | Introduction to course/expectations, Intro to R/RStudio, Functions, Vectors, Data Types                               | RLSB 2S014/ 2S018 | Meike      |
| [2](weeks/week_02.qmd)  | 1/17 | Loading Data, data.frames, and ggplot2                                                                                | RPV 1217          | Meike      |
| [3](weeks/week_03.qmd)  | 1/24 | dplyr: subsetting using filter()/select()                                                                             | RLSB 2S014/ 2S018 | Emile      |
| [4](weeks/week_04.qmd)  | 1/31 | dplyr: mutate(),across(), case_when(), factors, ggplot2 boxplots, facets, scales                                      | RPV 1217          | Emile      |
| [5](weeks/week_05.qmd)  | 2/7  | summarize() and group_by(), doing things with multiple tables (left_join() etc), reshaping data (i.e. pivot_longer()) | RLSB 2S014/ 2S018 | Meike      |
|                         | 2/7  | **Take Home Midterm Assigned**                                                                                        |                   |            |
| [6](weeks/week_06.qmd)  | 2/14 | More data wrangling practice                                                                                          | RPV 1217          | Meike      |
|                         |      |                                                                                                                       |                   |            |
| [7](weeks/week_07.qmd)  | 2/21 | More data wrangling practice                                                                                          | RPV 1217          | Meike      |
|                         | 2/25 | **Take home midterm due (Sunday)**                                                                                    |                   |            |
| [8](weeks/week_08.qmd)  | 2/28 | Intro to functions, working with lists                                                                                | RPV 1217          | Emile      |
| [9](weeks/week_09.qmd)  | 3/6  | Intro to functions, working with lists cont'd                                                                         | RLSB 2S014/ 2S018 | Emile      |
|           10            | 3/10 | **Final Project Assigned (Monday)**                                                                                   |                   |            |
| [10](weeks/week_10.qmd) | 3/13 | Functions/batch processing/purrr; Intro to stats/formulas/broom/More Purrr                                            | RPV 1217          | Emile      |
|           11            | 3/20 | No Class, Office Hour                                                                                                 | RPV 1217          |            |
|                         | 3/22 | **Final Project Due**                                                                                                 |                   |            |