---
title: "Week 10"
description: "More stats and purrr"
date: "03/13/2025"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

## Announcements

<!-- * Grades for midterm projects will be released in 1-2 days.  -->
<!--     * You will be notified by Sakai via your OHSU email address when grades are released.  -->
<!--     * Please review the comments and let us know if you have any questions.  -->
* _Please fill out the course evaluations for the class._ 
    * Course evaluations are very helpful for making improvements to our classes. 
    * If too few students fill out the evaluations, they are not released to us.
    * You might have two evaluations since there are two instructors. 


<!-- * Final exam will be posted soon.  -->


### Reminder to fill out post-class surveys

* This is a reminder that 5% of your grade is based on filling out [post-class surveys](https://ohsu.ca1.qualtrics.com/jfe/form/SV_dhbhugCU2UnjYOi) as a way of telling us that you came to class and engaged with the material for that week.
* You only need to fill out 5 surveys (of the 10 class sessions) for the full 5%. We encourage you to fill out as many surveys as possible to provide feedback on the class though.
* __Please fill out surveys by 8 pm on Sunday evenings to guarantee that they will be counted.__ We usually download them some time on Sunday evening or Monday. If you turn it in before we download the responses, it will get counted. 

_See [syllabus section on Post-class surveys](https://niederhausen.github.io/BSTA_526_W25/syllabus.html#post-class-surveys)_



## Topics

### Part 9

- **Use** `map()` functions from the `purrr` package to iterate functions
- **Nest** datasets into list-columns, and iterate statistical modeling and/or visualization functions over those elements
- **Use** `map2()` from the `purrr` package to iterate functions across two inputs
- **Learn** how to iterate regression modeling across different model variables 

## Class materials

Readings are linked below, and we are using the part_08 material on Dropbox

* [Week 10 Readings](../readings/10-reading.qmd)
* Dropbox [part_09 Project folder](https://www.dropbox.com/scl/fo/rovllkq3xlopagm0sbxzj/ABM98XUq_9iKejQtv9yZPRo?rlkey=6neu91bghsns7tk2z8k2yvquh&st=mw0r9x5l&dl=0)


## Post-class survey

* Please fill out the [post-class survey](https://ohsu.ca1.qualtrics.com/jfe/form/SV_dhbhugCU2UnjYOi) to provide feedback. Thank you!
* Previous muddiest points and clearest points with responses are collected here: <https://niederhausen.github.io/BSTA_526_W25/survey_feedback_previous_years>


## Homework

* See Dropbox folder for homework assignment.


## Recording

* __In-class__ recording links are on [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-526-1-21901-W25). Navigate to _Course Materials_ -> _Schedule with links to in-class recordings_. Note that the password to the recordings is at the top of the page. 

