---
title: "Week 4"
description: "`mutate()`, `case_when()`, `summarize()`, `group_by()`, `across()`, more `ggplot2`"
date: "1/30/2025"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---


## Topics

- **Learn** and apply `mutate()` to change the data type of a variable
- **Apply** `mutate()` to calculate a new variable based on other variables in a `data.frame`.
- **Apply** `case_when` in a `mutate()` statement to make a continuous variable categorical
- **Learn** how to `mutate()` `across()` multiple columns at once.
- **Learn** how to `summarize()` data with `group_by()` to summarize within categories
- **Learn** to facet and change scales/palettes of ggplots.


## Announcements

* Class materials for BSTA 526 will be provided in the shared Dropbox folder [BSTA_526_W25_class_materials_public](https://www.dropbox.com/scl/fo/rovllkq3xlopagm0sbxzj/ABM98XUq_9iKejQtv9yZPRo?rlkey=6neu91bghsns7tk2z8k2yvquh&st=mw0r9x5l&dl=0). 
* For today's class, make sure to download to your computer the folder called `part_04`, and then open RStudio by double-clicking on the file called `part_04.Rproj`.
* If you have not already done so, please join the [BSTA 526 Slack channel](https://join.slack.com/t/bsta526w25/shared_invite/zt-2x4jl264g-KV9YvPTAqKWuEBB1gE10BA) and introduce yourself by posting in the `#random` channel.


## Class materials

* [Readings](../readings/04-reading.qmd)
* Dropbox [part_04 Project folder](https://www.dropbox.com/scl/fo/rovllkq3xlopagm0sbxzj/ABM98XUq_9iKejQtv9yZPRo?rlkey=6neu91bghsns7tk2z8k2yvquh&st=mw0r9x5l&dl=0)

## Post-class survey

* Please fill out the [post-class survey](https://ohsu.ca1.qualtrics.com/jfe/form/SV_dhbhugCU2UnjYOi) to provide feedback. Thank you!
* Previous muddiest points and clearest points with responses are collected here: <https://niederhausen.github.io/BSTA_526_W25/survey_feedback_previous_years>


## Homework

* See Dropbox folder for homework assignment.
* HW 4 due on 2/6.

## Recording

* __In-class__ recording links are on [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-526-1-21901-W25). Navigate to _Course Materials_ -> _Schedule with links to in-class recordings_. Note that the password to the recordings is at the top of the page. 

