---
title: "Week 3"
description: "Errors, more data loading, data manipulation, ggplot themes, factors"
date: "1/23/2025"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---


## Topics

* Where to get help on errors
* Revisiting data loading with the `here` package
* Data manipulation with `dplyr` package
* Themes in the `ggplot2` package
* Factors
* Boxplots and facets


## Announcements

* Class materials for BSTA 526 will be provided in the shared Dropbox folder [BSTA_526_W25_class_materials_public](https://www.dropbox.com/scl/fo/rovllkq3xlopagm0sbxzj/ABM98XUq_9iKejQtv9yZPRo?rlkey=6neu91bghsns7tk2z8k2yvquh&st=mw0r9x5l&dl=0). 
* For today's class, make sure to download to your computer the folder called `part_03`, and then open RStudio by double-clicking on the file called `part_03.Rproj`.
* If you have not already done so, please join the [BSTA 526 Slack channel](https://join.slack.com/t/bsta526w25/shared_invite/zt-2x4jl264g-KV9YvPTAqKWuEBB1gE10BA) and introduce yourself by posting in the `#random` channel.


## Class materials

* [Readings](../readings/03-reading.qmd)
* Dropbox [part_03 Project folder](https://www.dropbox.com/scl/fo/rovllkq3xlopagm0sbxzj/ABM98XUq_9iKejQtv9yZPRo?rlkey=6neu91bghsns7tk2z8k2yvquh&st=mw0r9x5l&dl=0)

## Post-class survey

* Please fill out the [post-class survey](https://ohsu.ca1.qualtrics.com/jfe/form/SV_dhbhugCU2UnjYOi) to provide feedback. Thank you!
* Previous muddiest points and clearest points with responses are collected here: <https://niederhausen.github.io/BSTA_526_W25/survey_feedback_previous_years>

## Homework

* See Dropbox folder for homework assignment.
* HW 3 due on 1/30.

## Recording

* __In-class__ recording links are on [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-526-1-21901-W25). Navigate to _Course Materials_ -> _Schedule with links to in-class recordings_. Note that the password to the recordings is at the top of the page. 


