---
title: "Week 4 Readings"
linktitle: "Wk 4 Readings"
description: "`mutate()`, `across()`, summarize(), group_by(), ggplot: faceting, scales"
date: "2025-01-30"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

## Required

- [Data Transformation (3.1-3.3)](https://r4ds.hadley.nz/data-transform) from R for Data Science
- [`group_by()` Data Transformation (3.5-3.6)](https://r4ds.hadley.nz/data-transform.html#groups) from R for Data Science (2e)
    + The 1st edition's [Section 5.6 on Grouped summaries with `summarise()`](https://r4ds.had.co.nz/transform.html#grouped-summaries-with-summarise) is more detailed (wordier) and worth looking at as well.
    + The 1st edition also has [Section 5.7 on Grouped mutates (and filters)](https://r4ds.had.co.nz/transform.html#grouped-mutates-and-filters) that I did not see in the 2nd edition. _Please let me know if you find this content in the 2nd edition!_
- [Aggregating data with `summarize` and `map`](https://ubc-dsci.github.io/introduction-to-datascience/wrangling.html#aggregating-data-with-summarize-and-map) - we will cover `map()` and `rowwise()` later, but `summarize` and `mutate` with `across` are described here. You may want to re-visit this when we get to `purrr`.
- [ggplot2: Elegant Graphics for Data Analysis, Scales & Guides](https://ggplot2-book.org/scales-guides.html)
- [R for Data Science: Factors](https://r4ds.hadley.nz/factors.html) - we will continue to work with factors in the next few classes with `forcats` examples like provided here.

## Optional

- [Tidyverse style guide](https://style.tidyverse.org/index.html)
- [Advanced R: style guide](http://adv-r.had.co.nz/Style.html)
- `across()`: This [column-wise operations vignette](https://cran.r-project.org/web/packages/dplyr/vignettes/colwise.html) will be useful for the next couple classes.
