---
title: "Week 10 Readings"
linktitle: "Wk 10 Readings"
description: "More stats, broom, and tables (gt, gtsummary)"
date: "2024-03-13"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---


## Required

- [Introduction to map()](https://jennybc.github.io/purrr-tutorial/ls01_map-name-position-shortcuts.html) - Jenny Bryan
- [Purrr Tips and Tricks](https://www.emilhvitfeldt.com/post/2018-01-08-purrr-tips-and-tricks/) by Emil Hvitfeldt.
- [Introduction to broom](https://cran.r-project.org/web/packages/broom/vignettes/broom.html)


## Suggested

- More on using map and nested data with modeling: [R for Data Science: Many Models, First edition](https://r4ds.had.co.nz/many-models.html)
- [broom and dplyr](https://broom.tidymodels.org/articles/broom_and_dplyr.html)
- [Joy of Functional programming talk by Hadley Wickham](https://learning.acm.org/techtalks/functionalprogramming) - more on nesting/iteration

For learning more about statistics with R:

- Modern Dive / Statistical Inference via Data Science by Chester Ismay and Albert Y Kim is a nice place to start: <https://moderndive.com/>
- Danielle Navarro's Learning Statistics with R is excellent and talks much more about statistics: <https://learningstatisticswithr.com/>
- [Model Basics](https://r4ds.had.co.nz/model-basics.html) from R for Data Science
- More on survival analysis in R
  * [Survival Analysis in R Tutorial by Dr. Emily C Zabor](https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html)
  * [Survminer survival plot vignette](https://cran.r-project.org/web/packages/survminer/vignettes/Informative_Survival_Plots.html)
  * [UVA's Survival Workshop materials](https://bioconnector.github.io/workshops/r-survival.html)
  * [Rview's Survival Analysis](https://rviews.rstudio.com/2017/09/25/survival-analysis-with-r/)


- [Programming with dplyr](https://dplyr.tidyverse.org/articles/programming.html) - in case I can't get to tidyeval use for functions with tidyverse
- [ggplot2 in packages](https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html) - examples how to use ggplot inside functions
- Resources for learning more statistics:
  * Modern Dive / Statistical Inference via Data Science by Chester Ismay and Albert Y Kim is a nice place to start: <https://moderndive.com/>
  * Danielle Navarro's Learning Statistics with R is excellent and talks much more about statistics: <https://learningstatisticswithr.com/>
- More on using map and nested data with modeling: [R for Data Science: Many Models](https://r4ds.had.co.nz/many-models.html)
- [broom and dplyr](https://broom.tidymodels.org/articles/broom_and_dplyr.html)
- Useful vignettes on table output: [gtsummary intro to tbl_summary](https://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html)
- Ted Laderas's interactive workbook on learning rowwise and nested data: [learning rowwise](https://tladeras.shinyapps.io/learning_rowwise)
- We might not get to dates but in case you want to learn more: [Dates and times in R for Data Science](https://r4ds.had.co.nz/dates-and-times.html)
- If you want to learn about tidymodels: [Introduction to Machine Learning with the Tidyverse](https://education.rstudio.com/blog/2020/02/conf20-intro-ml/)
- [Joy of Functional programming talk by Hadley Wickham](https://learning.acm.org/techtalks/functionalprogramming) - more on nesting/iteration
- More on model building and machine learning
  * [Model Building](https://r4ds.had.co.nz/model-building.html) from R for Data Science
  * [Many Models](https://r4ds.had.co.nz/many-models.html) - from R for Data science. Covers `group_by()/nest()` and list-columns
  * [Tidymodels with R: Recipes](https://www.tmwr.org/recipes.html)
  * [Tidymodels with R: Fitting Models with Parsnip](https://www.tmwr.org/models.html)
  * [Tidymodels with R: Judging Model Effectiveness](https://www.tmwr.org/performance.html)
  * [UMAP and Cocktail Recipes](https://juliasilge.com/blog/cocktail-recipes-umap/)
  * [Tidymodels: K-means](https://www.tidymodels.org/learn/statistics/k-means/)
  * [PCA and Penguins](https://allisonhorst.github.io/palmerpenguins/articles/articles/pca.html)
